Add option to update service after pushing image

diff --git a/bin/ecs-build-and-push b/bin/ecs-build-and-push
--- a/bin/ecs-build-and-push
+++ b/bin/ecs-build-and-push
@@ -1,5 +1,5 @@
 #!/bin/bash
-#set -o xtrace
+set -o xtrace
 
 $(aws ecr get-login --profile=home)
 
@@ -17,6 +17,11 @@ docker tag ${name}:latest ${url}/${name}:latest && \
 docker push ${url}/${name}:${tag} && \
 docker push ${url}/${name}:latest
 
+if [[ "$?" != '0' ]]; then
+  echo "Error building and pushing image"
+  exit 1
+fi
+
 echo "Built and pushed ${name}:${tag}"
 
 if [ -f ECS_TASK_DEF ]; then
@@ -24,4 +29,15 @@ if [ -f ECS_TASK_DEF ]; then
   json=${json//LATEST_TAG/$tag}
   taskArn=$(aws --profile=home ecs register-task-definition --cli-input-json "$json" | json taskDefinition.taskDefinitionArn)
   echo "New task definition: $taskArn"
+
+  if [[ "$1" == 'deploy' ]]; then
+    echo "Updating service definition"
+    result=$(aws --profile=home ecs update-service --cluster=sites --service=$name --task-definition=$taskArn)
+    if [[ "$?" != '0' ]]; then
+      echo "Error deploying image: $result"
+      exit 1
+    fi
+  fi
 fi
+
+echo "Done!"
